-- test/parity.lua — proves the Lua scoring port agrees with the website.
--
-- The TypeScript engine (app/lib/loot-advisor.ts) is the ORACLE. fixtures.lua
-- carries its inputs AND its results, generated by
-- /api/loot-advisor/parity-fixtures. This script scores the same inputs in Lua
-- and reports every field that differs.
--
-- No game, no group, no raid — this is the whole reason the scorer is pure Lua.
--
--   cd loot-advisor-addon
--   curl -s localhost:3000/api/loot-advisor/parity-fixtures -o test/fixtures.lua
--   lua test/parity.lua
--
-- Exit status is 0 only when every case matches, so CI can gate on it.

package.path = "./?.lua;" .. package.path
local Scoring = require("Scoring")

local ok, fixtures = pcall(dofile, "test/fixtures.lua")
if not ok or type(fixtures) ~= "table" then
  io.stderr:write("could not load test/fixtures.lua — regenerate it first:\n")
  io.stderr:write("  curl -s localhost:3000/api/loot-advisor/parity-fixtures -o test/fixtures.lua\n")
  os.exit(2)
end

-- Fields compared per case. Every one of them is a real branch in the engine,
-- so a mismatch anywhere is a genuine divergence rather than cosmetic drift.
local FIELDS = {
  "raw_score", "badge", "ilvl_delta", "track_gap", "stat_alignment",
  "tier_bonus", "declared_need", "is_ranked_override", "ranked_tier", "is_upgrade",
}

local function describe(inp)
  return string.format(
    "slot=%s stats=%s spec=%s tier=%s eq=%d/%s pieces=%d owns=%s",
    inp.slot, inp.stat_label, inp.spec_label,
    tostring(inp.ranked_tier) .. "/" .. tostring(inp.bis),
    inp.equipped_ilvl, inp.equipped_track, inp.piece_count, tostring(inp.already_owns)
  )
end

local total, failed = 0, 0
local firstFailures = {}
local byField = {}

for _, case in ipairs(fixtures) do
  total = total + 1
  local inp = case.input

  local candidate = {
    equipped_ilvl  = inp.equipped_ilvl,
    equipped_track = inp.equipped_track,
    piece_count    = inp.piece_count,
    declared_need  = false,
    ranked_tier    = inp.ranked_tier,
    -- The BIS signal. Omitting it here made 276k cases run with bis = nil on the
    -- Lua side while the TS oracle had it set, so the harness reported a
    -- divergence that was its OWN blind spot rather than the port's.
    bis            = inp.bis,
    already_owns   = inp.already_owns,
    owned_ilvl     = inp.owned_ilvl,
  }
  local item = { slot = inp.slot, is_tier = inp.is_tier, stats = inp.stats }

  local got = Scoring.scoreCandidate(
    candidate, item, inp.spec, inp.candidate_ilvl, inp.candidate_track
  )

  local bad = {}
  for _, f in ipairs(FIELDS) do
    local a, b = got[f], case.expected[f]
    -- nil and false are distinct in Lua but both falsy; compare directly so a
    -- nil-vs-false divergence is caught rather than silently passing.
    if a ~= b then
      bad[#bad + 1] = string.format("%s: lua=%s ts=%s", f, tostring(a), tostring(b))
      byField[f] = (byField[f] or 0) + 1
    end
  end

  if #bad > 0 then
    failed = failed + 1
    if #firstFailures < 10 then
      firstFailures[#firstFailures + 1] = describe(inp) .. "\n      " .. table.concat(bad, "\n      ")
    end
  end
end

print(string.format("parity: %d cases, %d matched, %d differed", total, total - failed, failed))

if failed > 0 then
  print("\nmismatches by field:")
  for _, f in ipairs(FIELDS) do
    if byField[f] then print(string.format("  %-20s %d", f, byField[f])) end
  end
  print("\nfirst " .. #firstFailures .. " failing cases:")
  for i, s in ipairs(firstFailures) do print("  " .. i .. ". " .. s) end
  os.exit(1)
end

print("PASS — the Lua port agrees with the website on every case.")
os.exit(0)
